### ISSUE TITLE
would this handle Microsoft Edge?

### ISSUE THREAD

**Issue by efx** [lifeart/ember-cli-fallback-builds#9]
I recently found Edge doesn't support as much of ES2015 as I thought.
Would this addon help me build polyfills specific to Edge? If so, do you have an example?
I can update the documentation with such an example.

**Comment by lifeart** [comment]
@efx targets config should be ok for your case.

![image](https://user-images.githubusercontent.com/1360552/64352787-4c001b00-d005-11e9-8ed6-7d85e3651537.png)

**Comment by efx** [comment]
Thanks @lifeart. I'll try it with my `targets` and see.
